// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txsqzwjlwxugflgdzxgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4c3F6d2psd3h1Z2ZsZ2R6eGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDY3NjYsImV4cCI6MjA2NTcyMjc2Nn0.XtQDdf8mrX3NzWk2w1wXnb0BbtK2GfjOYs4xan_VLeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);